# This komorebi setting will be used for tray context menu.
# If you don't use komorebi, you can remove this section.

# This is the main configuration file for Yet Another Status Bar (YASB)
bars:
  status-bar:
    enabled: true
    #screens: ['DELL P2419H (1)'] 
    #screens: ['DELL P2419H (2)'] 
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true 
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 3
      bottom: 0
      right: 3
    widgets:
      left:
        [
       "home",
       "apps",
        ] 
      center: [
        "traffic",
        "server_monitor",
        ]
        
      right:
        [
          "media",
          #"systray",
          "cpu",
          "memory",
          #"gpu",
          "disk",
          "volume",
          #"weather",
          "clock",
          "power_menu",
        ]
widgets:

battery:
      type: "yasb.battery.BatteryWidget"
      options:
        label: "<span>{icon}</span>{percent}%"
        label_alt: "{icon} {percent}% | time: {time_remaining}"
        charging_options:
          icon_format: "{charging_icon}"

clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\uf017 {%H:%M:%S}"
      label_alt: "\uf017 {%H:%M %d-%m-%y}"
      timezones: []
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        show_holidays: true
        holiday_color: "#ff9f00"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"

memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "MEM: {virtual_mem_percent}% | USO: {virtual_mem_used}"
      label_alt: "MEM: {virtual_mem_percent}% | USO: {virtual_mem_used} | FREE: {virtual_mem_free} | Total: {virtual_mem_total}"
      update_interval: 2000
      progress_bar:
        enabled: true
        size: 20
        thickness: 2
        color: "#ffffff"
        background_color: "#242739"
      callbacks:
        on_left: "toggle_label"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "CPU {info[percent][total]:.0f}%"
      label_alt: "CPU {info[percent][total]:.0f}% {info[histograms][cpu_percent]}"
      update_interval: 2000
      progress_bar:
        enabled: true
        position: "left"
        size: 20
        thickness: 2
        color: "#ffffff"
        background_color: "#242739" 
      update_interval: 2000
      callbacks:
        on_right: "do_nothing"

weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "fce59cae3d97446eb46185418250307"
      update_interval: 600
      hide_decimal: true
      location: ' #--------------# ' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64

volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "<span>{volume}</span> {level}"
        volume_icons:
          - "<span class=\"mute\">\ueee8</span>"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"

power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Desligar"]
        restart: ["\uead2", "Reiniciar"]
        signout: ["\udb80\udf43", "sair"]
        hibernate: ["\uf28e", "Hibernar"]
        sleep: ["\u23fe", "Dormir"]
        cancel: ["\udb81\udf3a", "Cancelar"]
  apps:
      type: "yasb.applications.ApplicationsWidget"
      options:
        label: "{data}"
        app_list:
          - {icon: "\uf489", launch: "wt"}
          #- {icon: "\uf413", launch: "explorer c:\\Users\\amn"}
          #- {icon: "\udb82\ude1e", launch: "C:\\Users\\amn\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"}
          #- {icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"}
          #- {icon: "\uf0a2", launch: "notification_center"}
          #- {icon: "\ueb51", launch: "quick_settings"}
          #- {icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate"}
          #- {icon: "\uf422", launch: "search"}
          #- {icon: "\udb84\udf55", launch: "widget"}
          # Currently available to use quick_settings, notification_center, search, widget, launcher (launcher will trigger ALT+A)

win_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\ue62a"
        label_alt: "\ue62a"
        class_name: "system-widget"
        callbacks:
          on_left: "exec start_menu"
           
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\ueb01 </span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label_alt: "<span>\ueb01 </span> Download \uea9a {download_speed} | Upload \ueaa1 {upload_speed}"
      update_interval: 1000
      speed_unit: "bytes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
        on_right: "exec cmd.exe /c start ms-settings:network"
        
  server_monitor:
    type: "yasb.server_monitor.ServerMonitor"
    options:
        label: "<span>\uf510</span>"
        label_alt: "{online}/{offline} of {total}"
        ssl_check: true
        ssl_verify: true
        ssl_warning: 10
        timeout: 2
        update_interval: 20000
        desktop_notifications:
          ssl: true
          offline: true
        servers: [
          'google.com',
          'youtube.com',
        ]
        menu:
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
        callbacks:
          on_left: "toggle_menu"
          on_right: "toggle_label"
               
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true 
          blur: true
          round_corners: true
          border_color: None
          alignment: "center"
          distance: 5
        callbacks:
          on_left: "toggle_group" 
          
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_play_pause"
        on_right: "toggle_label"
      max_field_size:
        label: 16
        label_alt: 16
      show_thumbnail: false
      controls_only: false
      controls_left: false
      controls_hide: false
      thumbnail_edge_fade: true
      thumbnail_padding: 32
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"
        separator: " "
        label_padding: 2
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 80
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
             
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
      - { title: "notepad", path: "C:\\Windows\\notepad.exe" }
      system_menu: true
      power_menu: false
      blur: true
      border_color: "None"
      round_corners_type: "small"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      menu_labels:
       system: "Configurações do Sistema"
       about: "Sobre Este PC"
       task_manager: "Gerenciador de Tarefas"

systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false

gpu:
   type: "yasb.gpu.GpuWidget"
   options:
    label: "<span>\udb82\udcae</span> {info[utilization]}% | {info[temp]}°C"
    label_alt: "<span>\udb82\udcae</span> {info[utilization]}% | {info[temp]}°C | {info[mem_used]} | {info[mem_total]}"
    update_interval: 2000
    gpu_thresholds:
      low: 10
      medium: 50
      high: 90
    histogram_icons:
      - "\u2581" # 0%
      - "\u2581" # 10%
      - "\u2582" # 20%
      - "\u2583" # 30%
      - "\u2584" # 40%
      - "\u2585" # 50%
      - "\u2586" # 60%
      - "\u2587" # 70%
      - "\u2588" # 80%+
    histogram_num_columns: 8
    callbacks:
      on_left: toggle_label
