watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    animation:
      enabled: true
      duration: 800
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 13
      left: 20
      bottom: -9
      right: 20
    widgets:
      left: [
        "komorebi_workspaces",
        "taskbar",
      ]
      center: [        
        "active_window",]
      right: [
        "systray",
        #"volume",
        "language",
        "clock",
        "notifications",
 
        ]
widgets:
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
          on_left: "toggle_label"
      wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
      ] 
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%b %d, %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      tooltip: false
      timezones: []
      callbacks:
        on_left: "toggle_calendar"
      calendar: 
        blur: true
        round_corners: true
        border_color: None
        distance: 4
        alignment: "left"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: True
        round_corners: True
        border_color: None
        alignment: "right"
        direction: "down"
        distance: 4
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "{count} <span>\uf476</span>"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "do_nothing" 
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: False
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
          left: 0
          top: 0
          right: 0
          bottom: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation:
        enabled: true
        duration: 200
        type: "fadeInOut"
      title_label:
        enabled: false
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
        active_window:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
      rewrite:
      - pattern: "^(.+?)\\.exe$"
        replacement: "\\1"
        case: lower
      - pattern: "(.*)zen(.*)$"
        replacement: "browser \\2"
      - pattern: "(.*)applicationframehost(.*)$"
        replacement: "notepad \\2"
      - pattern: "(.*)microsoft.cmdpal.ui(.*)$"
        replacement: "Drun \\2"
      - pattern: "(.*)imageglass(.*)$"
        replacement: "Photos \\2" 
      - pattern: "(.*)robloxplayerbeta(.*)$"
        replacement: "Roblox \\2"
