name: Create Theme
on:
  issues:
    types: [opened]

env:
  PYTHON_VERSION: '3.14'

jobs:
  createPR:
    permissions: write-all
    name: Submit a theme
    runs-on: windows-latest
    if: startsWith(github.event.issue.title, '[create-theme]:')
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - name: Setup python modules
        run: |
          pip install requests pyyaml

      - name: Checkout YASB repo
        uses: actions/checkout@v6
        with:
          repository: amnweb/yasb
          path: yasb-repo

      - name: Install YASB dependencies
        run: |
          pip install ./yasb-repo

      - name: Setup Git
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create theme content
        env:
          THEME_AUTHOR: ${{ github.event.issue.user.login }}
        shell: bash
        run: |
          python .github/scripts/process-theme.py 2> error.log

      - name: Export creation output
        if: failure()
        shell: bash
        run: |
          cat error.log
          echo "CREATION_OUTPUT<<EOF" >> $GITHUB_ENV
          cat error.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Show error message
        if: failure()
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          comment: |
            # Theme Validation Error ❌

            It looks like there was a validation error with your submitted theme configuration. Please review the error message below, fix the issues in your YAML config, styles or image and submit a new request.

            ```text
            ${{ env.CREATION_OUTPUT }}
            ```

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        if: success()
        with:
          add-paths: themes/
          token: ${{ secrets.GITHUB_TOKEN  }}
          commit-message: "Add theme: ${{ env.THEME_NAME }}"
          delete-branch: true
          title: "Add theme: ${{ env.THEME_NAME }}"
          body: |
            # Add theme: ${{ env.THEME_NAME }}

            This PR adds a new theme to the theme library.

            ## Theme Details
            * **Name**: ${{ env.THEME_NAME }}
            * **Description**: ${{ env.THEME_DESCRIPTION }}
            * **Homepage**: ${{ env.THEME_HOMEPAGE }}
            * **Author**: @${{ env.THEME_AUTHOR }}
          base: main
          branch: create-theme-${{ github.event.issue.number }}
        
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          comment: |
            # Thank you for your contribution! :tada:

            Your theme has been successfully submitted. The maintainers will review it and get back to you soon.

            Here are some details about your submission:
            * Your theme has been requested into [this PR](https://github.com/amnweb/yasb-themes/pull/${{ env.PULL_REQUEST_NUMBER }}).
            * It has been created into the [create-theme-${{ github.event.issue.number }} branch](https://github.com/amnweb/yasb-themes/tree/create-theme-${{ github.event.issue.number }}).

            > If you have any questions or need help, feel free to ask in the comments below or in the PR.
